### PR TITLE
Testing run peekops using Ansible

### PR DESCRIPTION
**Pull request by tuanpembual**
I try solve this problems using ansible and vagrant. The solutions can pass all testing except net testing. I read network.js (as testing script for net) and I have make net rule base on this testing. But still can't pass.

Need correction and suggestion.

Thanks

### CODE REVIEW

**Comment by ruckuus** [comment]
@tuanpembual can you elaborate the error you have encountered? Debug log will be useful.

**Comment by tuanpembual** [comment]
here the error output:

npm test

> peekops@0.0.1 test /Users/log/jek/rant/ops/peekops
> mocha test/*.js

  Application
    ✓ should run Hello Ops on port 80

  Cache
    ✓ should run redis

  DB
    ✓ should run postgres

  System
    ✓ Run Ubuntu 64 bit.

  Web
    ✓ should run nginx on port 80

  Network
    1) "before all" hook

  5 passing (3m)
  1 failing

  1) Network "before all" hook:
     Error: timeout of 150000ms exceeded. Ensure the done() callback is being called in this test.

npm ERR! Test failed.  See above for more details.

**Comment by ruckuus** [comment]
@tuanpembual Have you tried to execute nmap directly against your VMs?

**Comment by tuanpembual** [comment]
nope.
I will try after this.
Thanks for sugestions. :)

**Pull request closed without merging**
