### PR TITLE
Customized Vagrantfile & new config folder inside solutions

### PR DESCRIPTION
**Pull request by dezieg**
Everything's running except the network.js. Have tried to edit the network.js and scan.js but still no clue. Kindly need a guidance.

### CODE REVIEW

**Comment by ruckuus** [comment]
Please put all scripts into PR.

**Comment by dezieg** [comment]
Done.. Please confim..

**Comment by dezieg** [comment]
Hi @ruckuus 

Please confirm, do I have this PR Completed ? or please if you have any suggestion.

Thanks

**Comment by ruckuus** [comment]
Thanks for your time @dezieg

**Pull request closed without merging**
